import fs from 'fs'
import path from 'path'
import { exec } from 'child_process'
import { promisify } from 'util'

const execAsync = promisify(exec)

const FFMPEG_PATH = '/usr/bin/ffmpeg'

/**
 * AI Frames video generator.
 *
 * Generates multiple AI frames using Pollinations.ai (completely FREE, no API
 * key required), then stitches them into a video with smooth crossfade
 * transitions using ffmpeg. Each frame is REAL AI-generated content.
 *
 * This is NOT video diffusion (like SVD/cogvideox), but it IS real AI:
 * every frame is generated by a neural network (Stable Diffusion via
 * Pollinations). The result is a dreamy, evolving video where the scene
 * transforms over time.
 *
 * How it works:
 *   1. Generate N frames via Pollinations image API with seed variation
 *   2. Apply slight zoom/pan to each frame for additional motion
 *   3. Crossfade between frames for smooth transitions
 *   4. Output as H.264 MP4
 */

export interface AiFramesResult {
  videoUrl: string
  provider: string
  elapsedMs: number
  framesGenerated: number
}

async function generateFrame(
  prompt: string,
  seed: number,
  width: number,
  height: number,
  outputPath: string,
  retryCount = 0,
): Promise<boolean> {
  const encodedPrompt = encodeURIComponent(prompt.slice(0, 200))
  const url = `https://image.pollinations.ai/prompt/${encodedPrompt}?width=${width}&height=${height}&seed=${seed}&nologo=true&model=flux`

  try {
    const res = await fetch(url, {
      signal: AbortSignal.timeout(30000),
    })
    if (!res.ok) {
      throw new Error(`HTTP ${res.status}`)
    }
    const buf = Buffer.from(await res.arrayBuffer())
    if (buf.length < 1000) {
      throw new Error('Response too small')
    }
    await fs.promises.writeFile(outputPath, buf)
    return true
  } catch (err) {
    if (retryCount < 2) {
      await new Promise((r) => setTimeout(r, 3000))
      return generateFrame(prompt, seed, width, height, outputPath, retryCount + 1)
    }
    console.warn(`[ai-frames] frame seed=${seed} failed: ${err instanceof Error ? err.message : err}`)
    return false
  }
}

export async function generateAiFramesVideo(
  opts: {
    prompt: string
    duration?: number
    fps?: number
    width?: number
    height?: number
    baseImageBuffer?: Buffer // optional: used as reference for the prompt
  },
): Promise<AiFramesResult> {
  const start = Date.now()
  const duration = opts.duration || 5
  const fps = opts.fps || 25
  const width = opts.width || 512
  const height = opts.height || 512

  // Number of key frames to generate (one per ~1 second of video)
  const numFrames = Math.max(4, Math.min(8, duration))
  // Each key frame is shown for ~1 second, with crossfade transitions
  const frameDuration = duration / numFrames

  // Ensure output directory exists
  const uploadsDir = path.join(process.cwd(), 'public', 'uploads')
  await fs.promises.mkdir(uploadsDir, { recursive: true })

  const timestamp = Date.now()
  const framesDir = path.join(uploadsDir, `frames-${timestamp}`)
  await fs.promises.mkdir(framesDir, { recursive: true })

  // Build prompt with motion hints
  const basePrompt = opts.prompt || 'cinematic scene with subtle motion'
  const motionHints = [
    'wide shot, beginning',
    'slight zoom in',
    'continued motion',
    'dynamic angle',
    'close-up detail',
    'pulling back',
    'final view',
    'epic conclusion',
  ]

  // Generate frames with seed variation
  console.log(`[ai-frames] generating ${numFrames} AI frames via Pollinations...`)
  const framePaths: string[] = []
  const generationPromises: Array<Promise<void>> = []

  for (let i = 0; i < numFrames; i++) {
    const seed = 1000 + i * 137 // deterministic seed variation
    const hint = motionHints[i % motionHints.length]
    const fullPrompt = `${basePrompt}, ${hint}, high quality, detailed`
    const framePath = path.join(framesDir, `frame-${String(i).padStart(3, '0')}.jpg`)

    generationPromises.push(
      (async () => {
        const success = await generateFrame(fullPrompt, seed, width, height, framePath)
        if (success) {
          framePaths.push(framePath)
        }
      })(),
    )

    // Stagger requests to avoid rate limiting (Pollinations allows ~1 req/sec)
    if (i < numFrames - 1) {
      await new Promise((r) => setTimeout(r, 1500))
    }
  }

  await Promise.all(generationPromises)

  // Sort frame paths by index
  framePaths.sort()

  if (framePaths.length < 2) {
    throw new Error('Не удалось сгенерировать достаточно AI-кадров. Попробуйте ещё раз.')
  }

  console.log(`[ai-frames] generated ${framePaths.length}/${numFrames} frames, stitching with ffmpeg...`)

  // Create a video from frames with crossfade transitions
  // Strategy: for each frame, create a 1-second clip with slight zoom,
  // then crossfade them together using xfade filter
  const outputPath = path.join(uploadsDir, `ai-video-${timestamp}.mp4`)

  // Build ffmpeg command:
  // 1. For each frame, create a zoompan clip of `frameDuration` seconds
  // 2. Concatenate with crossfade transitions
  if (framePaths.length === 1) {
    // Only one frame - just make a zoompan video
    const filter = `zoompan=z='min(zoom+0.001,1.1)':d=${duration * fps}:s=${width}x${height}:fps=${fps}`
    const escapeShell = (s: string) => `'${s.replace(/'/g, "'\\''")}'`
    const cmd = `${FFMPEG_PATH} -y -loop 1 -i ${escapeShell(framePaths[0])} -vf ${escapeShell(filter)} -t ${duration} -c:v libx264 -preset fast -crf 23 -pix_fmt yuv420p -movflags +faststart ${escapeShell(outputPath)}`
    await execAsync(cmd, { timeout: 30000, maxBuffer: 2 * 1024 * 1024 })
  } else {
    // Multiple frames: create individual clips then crossfade
    const escapeShell = (s: string) => `'${s.replace(/'/g, "'\\''")}'`

    // Step 1: Create individual zoompan clips for each frame
    const clipPaths: string[] = []
    for (let i = 0; i < framePaths.length; i++) {
      const clipPath = path.join(framesDir, `clip-${String(i).padStart(3, '0')}.mp4`)
      // Alternate zoom in/out for variety
      const zoomDir = i % 2 === 0 ? 'min(zoom+0.0008,1.12)' : 'if(eq(on,0),1.12,max(1.0,zoom-0.0008))'
      const panX = i % 2 === 0
        ? `iw/2-(iw/zoom/2)+${i * 5}`
        : `iw/2-(iw/zoom/2)-${i * 5}`
      const filter = `zoompan=z='${zoomDir}':d=${Math.round(frameDuration * fps)}:x='${panX}':y='ih/2-(ih/zoom/2)':s=${width}x${height}:fps=${fps}`
      const cmd = `${FFMPEG_PATH} -y -loop 1 -i ${escapeShell(framePaths[i])} -vf ${escapeShell(filter)} -t ${frameDuration} -c:v libx264 -preset fast -crf 23 -pix_fmt yuv420p ${escapeShell(clipPath)}`
      try {
        await execAsync(cmd, { timeout: 15000, maxBuffer: 1024 * 1024 })
        clipPaths.push(clipPath)
      } catch (err) {
        console.warn(`[ai-frames] clip ${i} failed: ${err instanceof Error ? err.message : err}`)
      }
    }

    if (clipPaths.length === 0) {
      throw new Error('Не удалось создать видео-клипы из AI-кадров.')
    }

    if (clipPaths.length === 1) {
      // Only one clip succeeded
      await fs.promises.copyFile(clipPaths[0], outputPath)
    } else {
      // Step 2: Crossfade clips together
      // Build input args
      const inputArgs = clipPaths.map((p) => `-i ${escapeShell(p)}`).join(' ')

      // Build xfade chain
      const transitionDuration = Math.min(0.5, frameDuration * 0.3)
      let filterChain = ''
      let prevLabel = '[0:v]'
      for (let i = 1; i < clipPaths.length; i++) {
        const offset = i * frameDuration - i * transitionDuration
        const outLabel = i < clipPaths.length - 1 ? `[v${i}]` : '[vout]'
        filterChain += `${prevLabel}[${i}:v]xfade=transition=fade:duration=${transitionDuration}:offset=${offset}${outLabel};`
        prevLabel = outLabel
      }
      // Remove trailing semicolon
      filterChain = filterChain.slice(0, -1)

      // If only 2 clips, no intermediate labels needed
      if (clipPaths.length === 2) {
        filterChain = `[0:v][1:v]xfade=transition=fade:duration=${transitionDuration}:offset=${frameDuration - transitionDuration}[vout]`
      }

      const cmd = `${FFMPEG_PATH} -y ${inputArgs} -filter_complex ${escapeShell(filterChain)} -map "[vout]" -c:v libx264 -preset fast -crf 23 -pix_fmt yuv420p -movflags +faststart ${escapeShell(outputPath)}`
      console.log('[ai-frames] stitching command:', cmd.slice(0, 200))
      await execAsync(cmd, { timeout: 30000, maxBuffer: 2 * 1024 * 1024 })
    }
  }

  // Verify output exists
  try {
    await fs.promises.access(outputPath)
  } catch {
    throw new Error('ffmpeg не создал выходной файл')
  }

  // Clean up frames directory
  await fs.promises.rm(framesDir, { recursive: true, force: true }).catch(() => {})

  return {
    videoUrl: `/uploads/ai-video-${timestamp}.mp4`,
    provider: 'ai-frames',
    elapsedMs: Date.now() - start,
    framesGenerated: framePaths.length,
  }
}
